### ISSUE TITLE
Fix photo carousel footer

### ISSUE THREAD

**Issue by jdliaw** [uclaacm/website#3]
Our photo carousel footer broke because we were pulling photos from Facebook, whose links expire. 

- [ ] Host photos elsewhere (Flickr)
- [ ] Update code to pull photos from this new source

**Comment by alexanderqchen** [comment]
Currently, the number of images have to be a multiple of 4 and be at least 12 in order to display correctly on normal screen size. If the number is not a multiple of 4, then there will be empty squares. On very wide screens, if there are fewer pictures than can be stretched across the width of the screen, the behavior is a little strange. There will be white space, but when a group of 4 pictures are unmounted, they are remounted after the last group of 4.

Hosting photos elsewhere will solve the majority of the issues, but we may need to consider changing the way images are mounted onto the dom in the future.

**Comment by alexanderqchen** [comment]
Update: Asked marketing director for pictures to display on website. Once pictures have been received, will put them on carousel.
