### ISSUE TITLE
SocialMedia component incorrectly uses type prop

### ISSUE THREAD

**Issue by mattxwang** [uclaacm/website#97]
While I'm on an issue grind...

I noticed that the `<SocialMedia>` component has an optional `type` prop. But, we render this prop directly into the `className` of the resulting icons, which means that we render a class `undefined` when the prop isn't used.

See `Home.js`; it has `.sm-icon .undefined` as its class signature:

![Screen Shot 2021-02-09 at 4 03 52 PM](https://user-images.githubusercontent.com/14893287/107445053-92a64e80-6af0-11eb-88be-46df91660f1e.png)

The short term solution is to use some sort of ternary before the render function in `<SocialMedia/>`, and render that; ex:

```jsx
const iconType = props.type ? props.type : "";

...
<button className={"sm-icon " + iconType}>...
```

Long-term though, we may want to evaluate how we implement these classes and/or how we define our components compositionally.

**Comment by vohndernet** [comment]
As a long term solution for whoever takes this, we can also switch this out for [react-icons](https://react-icons.github.io/react-icons) instead, which both takes care of this issue and removes how we're literally storing these pngs in our codebase. It'll also make updating the icons easier, like how facebook now has a circular icon instead of the square we currently deploy on our site!
